name = "compgrad_Rhapsodie"
uuid = "e05bbe28-0cd2-47b6-b799-e0d69634388a"
authors = ["Andr√© Ferrari <andferrari@gmail.com>"]
version = "0.1.0"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
EasyFITS = "a977f4a2-36a7-4172-89e7-19c2726f82e5"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FITSIO = "525bcba6-941b-5504-bd06-fd0dc1a4d2eb"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
InterpolationKernels = "16730964-a2ec-11e9-36fa-47a4f82bfac6"
LazyAlgebra = "aeaa251e-9d76-11e9-311b-83636bf44738"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
RhapsodieDirect = "0ed9b2bd-c76c-4f1a-94cb-965bde98f638"

[compat]
EasyFITS = "0.6.1"
FFTW = "1.10.0"
FITSIO = "0.17.5"
HDF5 = "0.17.2"
Images = "0.26.2"
LazyAlgebra = "0.2.7"
Plots = "1.40.19"
